# Generated by Django 5.0.14 on 2025-05-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Norma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(default="A definir", max_length=254)),
                ("tema", models.CharField(default="A definir", max_length=254)),
                ("emitente", models.CharField(default="A definir", max_length=254)),
                ("sistema", models.CharField(default="A definir", max_length=254)),
                ("codigo", models.CharField(default="A definir", max_length=254)),
                ("versao", models.IntegerField()),
                ("aprovacao", models.CharField(default="A definir", max_length=80)),
                ("instrucao_servico", models.CharField(default="A definir", max_length=20)),
                ("vigencia", models.DateField(blank=True, null=True)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="normas_pdfs/")),
            ],
        ),
    ]
