# Generated by Django 5.0.14 on 2025-05-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uecinormas", "0002_alter_norma_aprovacao_alter_norma_codigo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norma",
            name="instrucao_servico",
        ),
        migrations.AlterField(
            model_name="norma",
            name="vigencia",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
