# Generated by Django 5.0.14 on 2025-05-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uecinormas", "0003_remove_norma_instrucao_servico_alter_norma_vigencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norma",
            name="pdf",
        ),
    ]
