# Generated by Django 5.0.14 on 2025-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uecinormas", "0004_remove_norma_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norma",
            name="emitente",
        ),
        migrations.RemoveField(
            model_name="norma",
            name="sistema",
        ),
        migrations.RemoveField(
            model_name="norma",
            name="tema",
        ),
        migrations.RemoveField(
            model_name="norma",
            name="titulo",
        ),
        migrations.AddField(
            model_name="norma",
            name="anexo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="atualizacao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="categoria",
            field=models.CharField(blank=True, choices=[("GERAL", "Geral"), ("EXCLUSIVA", "Exclusiva")], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="edocs",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="errata",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="processo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="publicacao_dio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="revogada_dio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="norma",
            name="aprovacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="norma",
            name="codigo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="norma",
            name="versao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name="norma",
            name="vigencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="norma",
            name="vigencia",
            field=models.DateField(blank=True, null=True),
        ),
    ]
