# Generated by Django 5.2.1 on 2025-05-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('versao', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('data_vigencia', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('C', 'Criou'), ('U', 'Atualizou'), ('D', 'Deletou')], max_length=1)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField()),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('E', 'Em andamento'), ('C', 'Concluída')], default='A', max_length=1)),
                ('equipe', models.ManyToManyField(related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('obrigatorio', models.BooleanField(default=True)),
                ('resultado', models.CharField(blank=True, choices=[('C', 'Conforme'), ('N', 'Não conforme'), ('I', 'N/A')], max_length=1)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('comentarios', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ueciaudit.auditoria')),
            ],
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], max_length=1)),
                ('descricao', models.TextField()),
                ('corrigido', models.BooleanField(default=False)),
                ('data_correcao', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naos', to='ueciaudit.checklistitem')),
                ('responsavel_correcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('documentos', models.FileField(blank=True, null=True, upload_to='procedimentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='ueciaudit.norma')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ueciaudit.procedimento'),
        ),
    ]
